import { CncDailyReport, CncSheetRecord, DimensionRecord } from '../types';

export const createEmptySheetRecords = (): CncSheetRecord[] => {
  return [1, 2, 3, 4, 5, 6].map((num) => ({
    sheetNumber: num,
    processTime: '',
    delayTime: '',
    delayReason: '',
    setupTime: '',
    inspectionTime: '',
    productName: '',
    materialType: '',
    totalComponents: '',
    cutType: 'Cut',
    quality: 'OK',
  }));
};

export const createEmptyDimensionRecords = (): DimensionRecord[] => {
  return [1, 2, 3, 4, 5, 6].map((num) => ({
    sheetNumber: num,
    lengthMm: '',
    widthMm: '',
    thicknessMm: '',
    toleranceNotes: '',
  }));
};

export const createNewBlankReport = (operatorName = ''): CncDailyReport => {
  const now = new Date();
  const dateStr = now.toLocaleDateString('id-ID', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const randId = Math.floor(1000 + Math.random() * 9000);
  const id = `CNC-${now.getFullYear()}${(now.getMonth() + 1).toString().padStart(2, '0')}-${randId}`;

  return {
    id,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    operatorName,
    shift: 'Shift 1 (Pagi)',
    dayAndDate: dateStr,
    workStartTime: '',
    workEndTime: '',
    project: '',
    sasaNo: '',

    sectionA: {
      oilFillVolumeMl: '',
      oilLevel: 'Normal',
      bladeChanges: {
        vcut: { replaced: false, changeDate: '', toolCondition: '' },
        endmill3mm: { replaced: false, changeDate: '', toolCondition: '' },
        endmill6mm: { replaced: false, changeDate: '', toolCondition: '' },
      },
    },

    sectionB_Quick: createEmptySheetRecords(),
    sectionC_Tekma: createEmptySheetRecords(),

    sectionD: {
      ppG4mm: { lembar: '', sisa: '' },
      pp8mm: { lembar: '', sisa: '' },
      ppF10mm: { lembar: '', sisa: '' },
      otherMaterials: [],
    },

    sectionE: createEmptyDimensionRecords(),

    sectionF: {
      otherWork: '',
      messageOrInfo: '',
      issues: '',
    },

    status: 'DRAFT',
    supervisorToken: `spv_${Math.random().toString(36).substring(2, 10)}`,
    gmToken: `gm_${Math.random().toString(36).substring(2, 10)}`,
    supervisorName: 'Mulyana',
    gmName: 'Arifin',
    timeline: [],
  };
};

export const createSampleFilledReport = (operatorName = 'Ahmad Fauzi'): CncDailyReport => {
  const blank = createNewBlankReport(operatorName);
  const isoDate = new Date().toISOString().split('T')[0];

  return {
    ...blank,
    workStartTime: '08:00',
    workEndTime: '16:30',
    project: 'Project Box Packaging SASA 250g',
    sasaNo: `SPK-SASA-9941`,

    sectionA: {
      oilFillVolumeMl: 250,
      oilLevel: 'Normal',
      bladeChanges: {
        vcut: { replaced: true, changeDate: isoDate, toolCondition: 'Baru ganti mata pisau 90 deg' },
        endmill3mm: { replaced: false, changeDate: '2026-09-20', toolCondition: 'Kondisi tajam' },
        endmill6mm: { replaced: false, changeDate: '2026-09-18', toolCondition: 'Kondisi tajam' },
      },
    },

    sectionB_Quick: [
      {
        sheetNumber: 1,
        processTime: 45,
        delayTime: 5,
        delayReason: 'Pembersihan sisa bram',
        setupTime: 15,
        inspectionTime: 10,
        productName: 'Part Cover Luar SASA',
        materialType: 'PP 6mm',
        totalComponents: 48,
        cutType: 'Vcut + Cut',
        quality: 'OK',
      },
      {
        sheetNumber: 2,
        processTime: 40,
        delayTime: 0,
        delayReason: '',
        setupTime: 10,
        inspectionTime: 8,
        productName: 'Part Cover Luar SASA',
        materialType: 'PP 6mm',
        totalComponents: 48,
        cutType: 'Vcut + Cut',
        quality: 'OK',
      },
      {
        sheetNumber: 3,
        processTime: 50,
        delayTime: 10,
        delayReason: 'Penyesuaian clamping',
        setupTime: 12,
        inspectionTime: 10,
        productName: 'Sekat Dalam Box SASA',
        materialType: 'PP 8mm',
        totalComponents: 32,
        cutType: 'Cut',
        quality: 'OK',
      },
      {
        sheetNumber: 4,
        processTime: 45,
        delayTime: 0,
        delayReason: '',
        setupTime: 10,
        inspectionTime: 8,
        productName: 'Sekat Dalam Box SASA',
        materialType: 'PP 8mm',
        totalComponents: 32,
        cutType: 'Cut',
        quality: 'OK',
      },
      {
        sheetNumber: 5,
        processTime: '',
        delayTime: '',
        delayReason: '',
        setupTime: '',
        inspectionTime: '',
        productName: '',
        materialType: '',
        totalComponents: '',
        cutType: 'Cut',
        quality: 'OK',
      },
      {
        sheetNumber: 6,
        processTime: '',
        delayTime: '',
        delayReason: '',
        setupTime: '',
        inspectionTime: '',
        productName: '',
        materialType: '',
        totalComponents: '',
        cutType: 'Cut',
        quality: 'OK',
      },
    ],

    sectionC_Tekma: [
      {
        sheetNumber: 1,
        processTime: 42,
        delayTime: 0,
        delayReason: '',
        setupTime: 15,
        inspectionTime: 10,
        productName: 'Tray Alas Bawah',
        materialType: 'PP 10mm',
        totalComponents: 24,
        cutType: 'Cut',
        quality: 'OK',
      },
      {
        sheetNumber: 2,
        processTime: 38,
        delayTime: 5,
        delayReason: 'Kalibrasi sumbu Z',
        setupTime: 10,
        inspectionTime: 8,
        productName: 'Tray Alas Bawah',
        materialType: 'PP 10mm',
        totalComponents: 24,
        cutType: 'Cut',
        quality: 'OK',
      },
      {
        sheetNumber: 3,
        processTime: '',
        delayTime: '',
        delayReason: '',
        setupTime: '',
        inspectionTime: '',
        productName: '',
        materialType: '',
        totalComponents: '',
        cutType: 'Cut',
        quality: 'OK',
      },
      {
        sheetNumber: 4,
        processTime: '',
        delayTime: '',
        delayReason: '',
        setupTime: '',
        inspectionTime: '',
        productName: '',
        materialType: '',
        totalComponents: '',
        cutType: 'Cut',
        quality: 'OK',
      },
      {
        sheetNumber: 5,
        processTime: '',
        delayTime: '',
        delayReason: '',
        setupTime: '',
        inspectionTime: '',
        productName: '',
        materialType: '',
        totalComponents: '',
        cutType: 'Cut',
        quality: 'OK',
      },
      {
        sheetNumber: 6,
        processTime: '',
        delayTime: '',
        delayReason: '',
        setupTime: '',
        inspectionTime: '',
        productName: '',
        materialType: '',
        totalComponents: '',
        cutType: 'Cut',
        quality: 'OK',
      },
    ],

    sectionD: {
      ppG4mm: { lembar: 4, sisa: '1/4 lembar potong sudut' },
      pp8mm: { lembar: 2, sisa: '1/2 lembar utuh' },
      ppF10mm: { lembar: 2, sisa: 'Bram halus / sisa tepi' },
      otherMaterials: [
        { id: '1', name: 'Acrylic Bening 3mm (List Tutup)', lembar: 1, sisa: 'Sisa potongan 20x50cm' },
      ],
    },

    sectionE: [
      { sheetNumber: 1, lengthMm: 1220, widthMm: 850, thicknessMm: 6.0, toleranceNotes: '+/- 0.2mm (Standar)' },
      { sheetNumber: 2, lengthMm: 1220, widthMm: 850, thicknessMm: 6.0, toleranceNotes: '+/- 0.2mm' },
      { sheetNumber: 3, lengthMm: 1200, widthMm: 600, thicknessMm: 8.0, toleranceNotes: '+/- 0.1mm' },
      { sheetNumber: 4, lengthMm: 1200, widthMm: 600, thicknessMm: 8.0, toleranceNotes: '+/- 0.1mm' },
      { sheetNumber: 5, lengthMm: '', widthMm: '', thicknessMm: '', toleranceNotes: '' },
      { sheetNumber: 6, lengthMm: '', widthMm: '', thicknessMm: '', toleranceNotes: '' },
    ],

    sectionF: {
      otherWork: 'Membersihkan meja vakum CNC Quick & Tekma, membuang gram plastik ke TPS daur ulang.',
      messageOrInfo: 'Shift 2 perlu melanjutkan pemotongan sheet 5 & 6 untuk part cover SASA batch B.',
      issues: 'Mata pisau End Mill 3mm agak tumpul di akhir shift 1, sudah disiapkan cadangan di laci tool room.',
    },
  };
};

export const INITIAL_REPORTS: CncDailyReport[] = [
  {
    ...createNewBlankReport('Ahmad Fauzi'),
    id: 'CNC-202609-001',
    createdAt: '2026-09-27T08:30:00.000Z',
    updatedAt: '2026-09-27T17:15:00.000Z',
    operatorName: 'Ahmad Fauzi',
    shift: 'Shift 1 (Pagi)',
    dayAndDate: 'Minggu, 27 September 2026',
    workStartTime: '08:00',
    workEndTime: '16:30',
    project: 'SOSA Gourmet Box Display 2026',
    sasaNo: 'SPK-SOSA-9941',
    status: 'APPROVED',
    supervisorToken: 'spv_tok_9941_mulyana',
    gmToken: 'gm_tok_9941_arifin',
    supervisorName: 'Mulyana',
    gmName: 'Arifin',
    supervisorApproval: {
      approvedAt: '2026-09-27T16:50:00.000Z',
      approverName: 'Mulyana',
      notes: 'Hasil potong rapi dan dimensi sesuai toleransi gambar kerja. Diteruskan ke GM.',
      decision: 'APPROVED',
    },
    gmApproval: {
      approvedAt: '2026-09-27T17:15:00.000Z',
      approverName: 'Arifin',
      notes: 'Disetujui. Lanjutkan produksi batch berikutnya.',
      decision: 'APPROVED',
    },
    timeline: [
      {
        role: 'OPERATOR',
        actorName: 'Ahmad Fauzi',
        action: 'SUBMITTED',
        fromStatus: 'DRAFT',
        toStatus: 'PENDING_SUPERVISOR',
        timestamp: '2026-09-27T16:35:00.000Z',
        note: 'Laporan kerja shift 1 selesai tanpa kendala fatal.',
      },
      {
        role: 'SUPERVISOR',
        actorName: 'Mulyana',
        action: 'APPROVED',
        fromStatus: 'PENDING_SUPERVISOR',
        toStatus: 'PENDING_GM',
        timestamp: '2026-09-27T16:50:00.000Z',
        note: 'Hasil potong rapi dan dimensi sesuai toleransi gambar kerja.',
      },
      {
        role: 'GM',
        actorName: 'Arifin',
        action: 'APPROVED',
        fromStatus: 'PENDING_GM',
        toStatus: 'APPROVED',
        timestamp: '2026-09-27T17:15:00.000Z',
        note: 'Disetujui. Lanjutkan produksi batch berikutnya.',
      },
    ],
  },
  {
    ...createNewBlankReport('Budi Santoso'),
    id: 'CNC-202609-002',
    createdAt: '2026-09-28T07:15:00.000Z',
    updatedAt: '2026-09-28T09:20:00.000Z',
    operatorName: 'Budi Santoso',
    shift: 'Shift 2 (Siang)',
    dayAndDate: 'Senin, 28 September 2026',
    workStartTime: '15:00',
    workEndTime: '23:00',
    project: 'Partisi Interior SOSA Seasoning Rack',
    sasaNo: 'SPK-SOSA-8820',
    status: 'PENDING_GM',
    supervisorToken: 'spv_tok_8820_mulyana',
    gmToken: 'gm_tok_8820_arifin',
    supervisorName: 'Mulyana',
    gmName: 'Arifin',
    supervisorApproval: {
      approvedAt: '2026-09-28T09:20:00.000Z',
      approverName: 'Mulyana',
      notes: 'Telah diperiksa. Jumlah komponen dan sisa material sudah balance.',
      decision: 'APPROVED',
    },
    timeline: [
      {
        role: 'OPERATOR',
        actorName: 'Budi Santoso',
        action: 'SUBMITTED',
        fromStatus: 'DRAFT',
        toStatus: 'PENDING_SUPERVISOR',
        timestamp: '2026-09-28T08:45:00.000Z',
        note: 'Selesai pemotongan material PP F 10mm.',
      },
      {
        role: 'SUPERVISOR',
        actorName: 'Mulyana',
        action: 'APPROVED',
        fromStatus: 'PENDING_SUPERVISOR',
        toStatus: 'PENDING_GM',
        timestamp: '2026-09-28T09:20:00.000Z',
        note: 'Telah diperiksa. Menunggu persetujuan GM Arifin.',
      },
    ],
  },
  {
    ...createNewBlankReport('Dedi Kurniawan'),
    id: 'CNC-202609-003',
    createdAt: '2026-09-28T12:00:00.000Z',
    updatedAt: '2026-09-28T12:05:00.000Z',
    operatorName: 'Dedi Kurniawan',
    shift: 'Shift 1 (Pagi)',
    dayAndDate: 'Senin, 28 September 2026',
    workStartTime: '08:00',
    workEndTime: '16:30',
    project: 'SOSA Promo Stand Hanger PP 8mm',
    sasaNo: 'SPK-SOSA-7712',
    status: 'PENDING_SUPERVISOR',
    supervisorToken: 'spv_tok_7712_mulyana',
    gmToken: 'gm_tok_7712_arifin',
    supervisorName: 'Mulyana',
    gmName: 'Arifin',
    timeline: [
      {
        role: 'OPERATOR',
        actorName: 'Dedi Kurniawan',
        action: 'SUBMITTED',
        fromStatus: 'DRAFT',
        toStatus: 'PENDING_SUPERVISOR',
        timestamp: '2026-09-28T12:05:00.000Z',
        note: 'Laporan telah diajukan ke Pak Mulyana untuk review.',
      },
    ],
  },
];
